### PR TITLE
Misc updates

### PR DESCRIPTION
**Pull request by nibalizer**
Dope module. Let me know if there are any other changes you'd like to see.

### CODE REVIEW

**Comment by juju4** [comment]
Thanks a lot @nibalizer 
missed this grpc options which seems not that all new as from 0.18 per https://falco.org/docs/grpc/
good to be disabled by default for now.

no interaction/adaptation needed on systemd hardening options?
only AF_PACKET is denied and AF_UNIX sockets are allowed. only one I can think off.
https://github.com/juju4/ansible-falco/blob/master/templates/systemd-falco.service.j2

for some reason, travis testing all failed
centos8-7: https://travis-ci.org/github/juju4/ansible-falco/jobs/707021614
```
       TASK [juju4.falco : yum | install falcosecurity repository] ********************

       fatal: [localhost]: FAILED! => {"changed": false, "dest": "/etc/yum.repos.d/falcosecurity.repo", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://falco.org/repo/falcosecurit-rpm.repo"}
```
typo https://falco.org/repo/falcosecurit*y*-rpm.repo

ubuntu focal and xenial, https://travis-ci.org/github/juju4/ansible-falco/jobs/707021616
```
       TASK [juju4.falco : configure falco] *******************************************

       fatal: [localhost]: FAILED! => {"changed": false, "checksum": "adcf03b376dce4c13ef19e8734349929664e3adf", "exit_status": 1, "msg": "failed to validate", "stderr": "Fri Jul 10 20:51:01 2020: Runtime error: error reading config file (/root/.ansible/tmp/ansible-tmp-1594414260.4150462-16305-107384165078031/source): gRPC threadiness must be greater than 0. Exiting.\n", "stderr_lines": ["Fri Jul 10 20:51:01 2020: Runtime error: error reading config file (/root/.ansible/tmp/ansible-tmp-1594414260.4150462-16305-107384165078031/source): gRPC threadiness must be greater than 0. Exiting."], "stdout": "", "stdout_lines": []}
```
I didn't see mention in documentation but seems need non-zero value, even if disabled.

**Comment by nibalizer** [comment]
Ok! I'm on it.


>  only AF_PACKET is denied and AF_UNIX sockets are allowed. only one I can think off.

I'm no expert on this. Do I need to widen this up?

> typo https://falco.org/repo/falcosecurit*y*-rpm.repo

Fixed 

> I didn't see mention in documentation but seems need non-zero value, even if disabled.

0.23.0 does require greater than zero, master (0.24.0 as of tomorrow) accepts 0 as written in my PR. Maybe I'll capture the output of falco-version or something and put some logic in.

```
throw logic_error("error reading config file (" + m_config_file +"): gRPC threadiness must be greater than 0"); 
```

**Comment by nibalizer** [comment]
@juju4 Ok I think I resolved all the relevant issues.  I tried the unix socket under the default systemd hardening and it worked (on debian).

**Comment by juju4** [comment]
LGTM. Thanks!

**Pull request merged**
